### ISSUE TITLE
Design domain model

### ISSUE THREAD

**Issue by josephmeredith** [JackWolfard/CS2340#6]
Brainstorm candidate classes/objects for the domain model. Filter those to get rid of inappropriate objects. Create the Domain Model for the application. Use the project description to brainstorm objects. List primary attributes and responsibilities. Note the RDD stereotype of the classes. Annotate relationships between objects (which objects need to use other objects). Show any multiplicity requirements.

**Comment by BradleyAllnutt** [comment]
the objects in the domain model are all classes that we makeunder the model tab
